gcp_source_project_service_account_key: /home/suds_kumar/de-mod-poc-bbc161a24bd3.json
gcp_target_project_service_account_key: /home/suds_kumar/de-mod-poc-bbc161a24bd3.json

lock_file_name: _locks/all.lock



# --------------------------------------------------------------------------------------
# These values can be set for running the --test option to test different bucket options
test_bucket_location: us
test_default_kms_key_name: projects/my_source_prj/locations/global/keyRings/my_ring/cryptoKeys/my_key
test_email_for_iam: test@google.com
test_logging_bucket: source_bucket-logs
test_logging_prefix: prefix-
test_storage_class: STANDARD
test_topic_name: my_topic
